# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


app_name = 'openhub_django'
urlpatterns = [
    url(
        regex="^PortfolioProjectActivity/~create/$",
        view=views.PortfolioProjectActivityCreateView.as_view(),
        name='PortfolioProjectActivity_create',
    ),
    url(
        regex="^PortfolioProjectActivity/(?P<pk>\d+)/~delete/$",
        view=views.PortfolioProjectActivityDeleteView.as_view(),
        name='PortfolioProjectActivity_delete',
    ),
    url(
        regex="^PortfolioProjectActivity/(?P<pk>\d+)/$",
        view=views.PortfolioProjectActivityDetailView.as_view(),
        name='PortfolioProjectActivity_detail',
    ),
    url(
        regex="^PortfolioProjectActivity/(?P<pk>\d+)/~update/$",
        view=views.PortfolioProjectActivityUpdateView.as_view(),
        name='PortfolioProjectActivity_update',
    ),
    url(
        regex="^PortfolioProjectActivity/$",
        view=views.PortfolioProjectActivityListView.as_view(),
        name='PortfolioProjectActivity_list',
    ),
	url(
        regex="^PortfolioProject/~create/$",
        view=views.PortfolioProjectCreateView.as_view(),
        name='PortfolioProject_create',
    ),
    url(
        regex="^PortfolioProject/(?P<pk>\d+)/~delete/$",
        view=views.PortfolioProjectDeleteView.as_view(),
        name='PortfolioProject_delete',
    ),
    url(
        regex="^PortfolioProject/(?P<pk>\d+)/$",
        view=views.PortfolioProjectDetailView.as_view(),
        name='PortfolioProject_detail',
    ),
    url(
        regex="^PortfolioProject/(?P<pk>\d+)/~update/$",
        view=views.PortfolioProjectUpdateView.as_view(),
        name='PortfolioProject_update',
    ),
    url(
        regex="^PortfolioProject/$",
        view=views.PortfolioProjectListView.as_view(),
        name='PortfolioProject_list',
    ),
	url(
        regex="^OutsideProject/~create/$",
        view=views.OutsideProjectCreateView.as_view(),
        name='OutsideProject_create',
    ),
    url(
        regex="^OutsideProject/(?P<pk>\d+)/~delete/$",
        view=views.OutsideProjectDeleteView.as_view(),
        name='OutsideProject_delete',
    ),
    url(
        regex="^OutsideProject/(?P<pk>\d+)/$",
        view=views.OutsideProjectDetailView.as_view(),
        name='OutsideProject_detail',
    ),
    url(
        regex="^OutsideProject/(?P<pk>\d+)/~update/$",
        view=views.OutsideProjectUpdateView.as_view(),
        name='OutsideProject_update',
    ),
    url(
        regex="^OutsideProject/$",
        view=views.OutsideProjectListView.as_view(),
        name='OutsideProject_list',
    ),
	url(
        regex="^ContributonsToPortfolioProject/~create/$",
        view=views.ContributonsToPortfolioProjectCreateView.as_view(),
        name='ContributonsToPortfolioProject_create',
    ),
    url(
        regex="^ContributonsToPortfolioProject/(?P<pk>\d+)/~delete/$",
        view=views.ContributonsToPortfolioProjectDeleteView.as_view(),
        name='ContributonsToPortfolioProject_delete',
    ),
    url(
        regex="^ContributonsToPortfolioProject/(?P<pk>\d+)/$",
        view=views.ContributonsToPortfolioProjectDetailView.as_view(),
        name='ContributonsToPortfolioProject_detail',
    ),
    url(
        regex="^ContributonsToPortfolioProject/(?P<pk>\d+)/~update/$",
        view=views.ContributonsToPortfolioProjectUpdateView.as_view(),
        name='ContributonsToPortfolioProject_update',
    ),
    url(
        regex="^ContributonsToPortfolioProject/$",
        view=views.ContributonsToPortfolioProjectListView.as_view(),
        name='ContributonsToPortfolioProject_list',
    ),
	url(
        regex="^OutsideCommitter/~create/$",
        view=views.OutsideCommitterCreateView.as_view(),
        name='OutsideCommitter_create',
    ),
    url(
        regex="^OutsideCommitter/(?P<pk>\d+)/~delete/$",
        view=views.OutsideCommitterDeleteView.as_view(),
        name='OutsideCommitter_delete',
    ),
    url(
        regex="^OutsideCommitter/(?P<pk>\d+)/$",
        view=views.OutsideCommitterDetailView.as_view(),
        name='OutsideCommitter_detail',
    ),
    url(
        regex="^OutsideCommitter/(?P<pk>\d+)/~update/$",
        view=views.OutsideCommitterUpdateView.as_view(),
        name='OutsideCommitter_update',
    ),
    url(
        regex="^OutsideCommitter/$",
        view=views.OutsideCommitterListView.as_view(),
        name='OutsideCommitter_list',
    ),
	url(
        regex="^MostCommit/~create/$",
        view=views.MostCommitCreateView.as_view(),
        name='MostCommit_create',
    ),
    url(
        regex="^MostCommit/(?P<pk>\d+)/~delete/$",
        view=views.MostCommitDeleteView.as_view(),
        name='MostCommit_delete',
    ),
    url(
        regex="^MostCommit/(?P<pk>\d+)/$",
        view=views.MostCommitDetailView.as_view(),
        name='MostCommit_detail',
    ),
    url(
        regex="^MostCommit/(?P<pk>\d+)/~update/$",
        view=views.MostCommitUpdateView.as_view(),
        name='MostCommit_update',
    ),
    url(
        regex="^MostCommit/$",
        view=views.MostCommitListView.as_view(),
        name='MostCommit_list',
    ),
	url(
        regex="^MostRecentCommit/~create/$",
        view=views.MostRecentCommitCreateView.as_view(),
        name='MostRecentCommit_create',
    ),
    url(
        regex="^MostRecentCommit/(?P<pk>\d+)/~delete/$",
        view=views.MostRecentCommitDeleteView.as_view(),
        name='MostRecentCommit_delete',
    ),
    url(
        regex="^MostRecentCommit/(?P<pk>\d+)/$",
        view=views.MostRecentCommitDetailView.as_view(),
        name='MostRecentCommit_detail',
    ),
    url(
        regex="^MostRecentCommit/(?P<pk>\d+)/~update/$",
        view=views.MostRecentCommitUpdateView.as_view(),
        name='MostRecentCommit_update',
    ),
    url(
        regex="^MostRecentCommit/$",
        view=views.MostRecentCommitListView.as_view(),
        name='MostRecentCommit_list',
    ),
	url(
        regex="^AffiliatedCommitter/~create/$",
        view=views.AffiliatedCommitterCreateView.as_view(),
        name='AffiliatedCommitter_create',
    ),
    url(
        regex="^AffiliatedCommitter/(?P<pk>\d+)/~delete/$",
        view=views.AffiliatedCommitterDeleteView.as_view(),
        name='AffiliatedCommitter_delete',
    ),
    url(
        regex="^AffiliatedCommitter/(?P<pk>\d+)/$",
        view=views.AffiliatedCommitterDetailView.as_view(),
        name='AffiliatedCommitter_detail',
    ),
    url(
        regex="^AffiliatedCommitter/(?P<pk>\d+)/~update/$",
        view=views.AffiliatedCommitterUpdateView.as_view(),
        name='AffiliatedCommitter_update',
    ),
    url(
        regex="^AffiliatedCommitter/$",
        view=views.AffiliatedCommitterListView.as_view(),
        name='AffiliatedCommitter_list',
    ),
	url(
        regex="^InfographicDetail/~create/$",
        view=views.InfographicDetailCreateView.as_view(),
        name='InfographicDetail_create',
    ),
    url(
        regex="^InfographicDetail/(?P<pk>\d+)/~delete/$",
        view=views.InfographicDetailDeleteView.as_view(),
        name='InfographicDetail_delete',
    ),
    url(
        regex="^InfographicDetail/(?P<pk>\d+)/$",
        view=views.InfographicDetailDetailView.as_view(),
        name='InfographicDetail_detail',
    ),
    url(
        regex="^InfographicDetail/(?P<pk>\d+)/~update/$",
        view=views.InfographicDetailUpdateView.as_view(),
        name='InfographicDetail_update',
    ),
    url(
        regex="^InfographicDetail/$",
        view=views.InfographicDetailListView.as_view(),
        name='InfographicDetail_list',
    ),
	url(
        regex="^Organization/~create/$",
        view=views.OrganizationCreateView.as_view(),
        name='Organization_create',
    ),
    url(
        regex="^Organization/(?P<pk>\d+)/~delete/$",
        view=views.OrganizationDeleteView.as_view(),
        name='Organization_delete',
    ),
    url(
        regex="^Organization/(?P<pk>\d+)/$",
        view=views.OrganizationDetailView.as_view(),
        name='Organization_detail',
    ),
    url(
        regex="^Organization/(?P<pk>\d+)/~update/$",
        view=views.OrganizationUpdateView.as_view(),
        name='Organization_update',
    ),
    url(
        regex="^Organization/$",
        view=views.OrganizationListView.as_view(),
        name='Organization_list',
    ),
	]
